version: "3.7"

services:
  app:
    container_name: app
    build:
        context: .
        dockerfile: Dockerfile
    command: yarn dev
    ports:
    - "8080:8080"

    volumes:
      - .:/app 
    working_dir: /app 
