version: "3.7"

services:
  app:
    container_name: app
    build:
        context: .
        dockerfile: Dockerfile
    command: yarn start
    ports:
    - "3000:3000"

    volumes:
      - .:/app 
    working_dir: /app 
