version: "3.7"

services:
  app:
    container_name: app
    build:
        context: .
        dockerfile: Dockerfile
    command: npm run dev
    ports:
    - "1234:1234"
    - "1235:1235"

    volumes:
      - .:/app 
    working_dir: /app 
